apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fruit
  annotations:
    nginx.org/rewrites: "serviceName=apple rewrite=/;serviceName=banana rewrite=/"
spec:
  ingressClassName: nginx
  rules:
  - host: "fruit.com"
    http:
      paths:
      - pathType: Prefix
        path: "/apple"
        backend:
          service:
            name: apple
            port:
              number: 80
      - pathType: Prefix
        path: "/banana"
        backend:
          service:
            name: banana
            port:
              number: 80

